name: Destroy Development

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  destroy-poc:
    environment: POC
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Az CLI Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - id: bicep-output
        shell: pwsh
        run: |
          $config = (Get-Content bicep/params/poc.json | ConvertFrom-Json)
          $deployment = az deployment sub show --name "waf-policy-$($config.parameters.environment.value)" | ConvertFrom-Json
          echo "resource_groups=$($deployment.properties.outputs.resourceGroups.value)" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append

      - shell: pwsh
        run: |
          $resourceGroups = ${{ steps.bicep-output.outputs.resource_groups }} | ConvertFrom-Json
          foreach ($resourceGroup in $resourceGroups) {
            az group delete --name $resourceGroup --yes
          }
