name: Destroy Development

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  terraform-destroy-poc:
    environment: POC
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
