name: Release to POC

on:
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  terraform-plan-and-apply-poc:
    environment: POC
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

